//Generic
export const FETCH_ERROR = "FETCH_ERROR"

// Products
export const PRODUCTS_LOADING = "PRODUCTS_LOADING"
export const PRODUCTS_LOADING_DONE = "PRODUCTS_LOADING_DONE"
export const PRODUCTS_ERROR = "PRODUCTS_ERROR"
export const SINGLE_PRODUCT_LOADING = "SINGLE_PRODUCT_LOADING"
export const SINGLE_PRODUCT_DONE = "SINGLE_PRODUCT_DONE"
export const SINGLE_PRODUCT_ERROR = "SINGLE_PRODUCT_ERROR"
export const BRANDS_CATEGORIES_LOADING = "BRANDS_CATEGORIES_LOADING"
export const BRANDS_CATEGORIES_LOADING_DONE = "BRANDS_CATEGORIES_LOADING_DONE"
export const BRANDS_CATEGORIES_ERROR = "BRANDS_CATEGORIES_ERROR"

// Featured products
export const FEAT_PRODUCTS_LOADING = "FEAT_PRODUCTS_LOADING"
export const FEAT_PRODUCTS_LOADING_DONE = "FEAT_PRODUCTS_LOADING_DONE"

// Filters
export const GET_PRODUCTS = "GET_PRODUCTS"
export const UPDATE_SORT = "UPDATE_SORT"
export const SORT_PRODUCTS = "SORT_PRODUCTS"
export const UPDATE_FILTERS = "UPDATE_FILTERS"
export const FILTER_PRODUCTS = "FILTER_PRODUCTS"
export const CLEAR_FILTERS = "CLEAR_FILTERS"

// Cart
export const ADD_ITEM = "ADD_PRODUCT"
export const UPDATE_ITEM = "UPDATE_ITEM"
export const DELETE_ITEM = "DELETE_ITEM"
export const CLEAR_CART = "CLEAR_CART"
export const UPDATE_CART = "UPDATE_CART"

// Order submission
export const ORDER_SUBMIT_IN_PROGRESS = "ORDER_SUBMIT_IN_PROGRESS"
export const ORDER_SUBMIT_DONE = "ORDER_SUBMIT_DONE"
export const ORDER_SUBMIT_ERROR = "ORDER_SUBMIT_ERROR"

// Orders
export const ORDERS_LOADING = "ORDERS_LOADING"
export const ORDERS_LOADING_DONE = "ORDERS_LOADING_DONE"
export const ORDERS_ERROR = "ORDERS_ERROR"
export const SINGLE_ORDER_LOADING = "SINGLE_ORDER_LOADING"
export const SINGLE_ORDER_DONE = "SINGLE_ORDER_DONE"
export const SINGLE_ORDER_ERROR = "SINGLE_ORDER_ERROR"

// Auth
export const LOGIN_IN_PROGRESS = "LOGIN_IN_PROGRESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_DONE = "LOGIN_DONE"
export const LOGOUT = "LOGOUT"
export const UPDATE_AUTH = "UPDATE_AUTH"
export const REGISTRATION_IN_PROGRESS = "REGISTRATION_IN_PROGRESS"
export const REGISTRATION_DONE = "REGISTRATION_DONE"
export const REGISTRATION_ERROR = "REGISTRATION_ERROR"
